Traceback (most recent call last):
  File "/Users/eustachelebihan/Development/radium-challenge/sam/train.py", line 44, in <module>
    sam_model = sam_model_registry[config.training.model_type](checkpoint=config.training.checkpoint)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eustachelebihan/miniforge3/envs/radium-py11/lib/python3.11/site-packages/segment_anything/build_sam.py", line 38, in build_sam_vit_b
    return _build_sam(
           ^^^^^^^^^^^
  File "/Users/eustachelebihan/miniforge3/envs/radium-py11/lib/python3.11/site-packages/segment_anything/build_sam.py", line 104, in _build_sam
    with open(checkpoint, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/radium-data/sam_vit_b_01ec64.pth'